esphome:
  name: airgradient-diy-pro
  platform: ESP8266
  board: d1_mini
  
font:
  - file: "gfonts://Roboto"
    id: opensans
    size: 14

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: pms5003

  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: SenseAir

i2c:
  sda: D2
  scl: D1
  scan: false

sensor:
  - platform: pmsx003
    type: PMSX003

    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
      id: pm1
      filters:
        - throttle: 10s
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      id: pm25
      filters:
        - throttle: 10s
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      id: pm10
      filters:
        - throttle: 10s

    # Uncomment to enable
    # pm_0_3um:
    #   name: pm_0_3um
    # pm_0_5um:
    #   name: pm_0_5um
    # pm_1_0um:
    #   name: pm_1_0um
    # pm_2_5um:
    #   name: pm_2_5um
    # pm_5_0um:
    #   name: pm_5_0um
    # pm_10_0um:
    #   name: pm_10_0um

    uart_id: pms5003

  - platform: sht3xd
    temperature:
      name: "Temperature"
      id: temp
    humidity:
      name: "Humidity"
      id: humid
    address: 0x44
    update_interval: 20s

  - platform: senseair
    co2:
      name: "CO2"
      id: co2
    update_interval: 10s
    uart_id: SenseAir

  - platform: sgp30
    eco2:
      name: "eCO2"
      id: eco2
      accuracy_decimals: 1
      filters:
        - throttle: 10s
    tvoc:
      name: "TVOC"
      id: tvoc
      accuracy_decimals: 1
      filters:
        - throttle: 10s
    store_baseline: yes
    address: 0x58
    update_interval: 1s

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(opensans), "%.1f°C", id(temp).state );
      it.printf(50, 0, id(opensans), "HUM: %.1f%%", id(humid).state );
      it.printf(0, 14, id(opensans), "CO2:  %.0fppm", id(co2).state );
      it.printf(0, 28, id(opensans), "PM2.5:  %.0fppm", id(pm25).state);
      it.printf(0, 42, id(opensans), "TVOC:  %.0fppb", id(tvoc).state);
# Enable logging
logger:


# Enable ESP native API
api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AirGradient DIY Pro Fallback"
    password: !secret fallback_wifi_password

captive_portal:
